- name: variable from files
  hosts: localhost
  vars_files:
   - vars.yaml
  tasks:
    - name: print override info
      vars:  # task level var
        course: "devops"
      ansible.builtin.debug:
        msg: "hi iam learning course {{course}} from trainer {{trainer}},duration {{duration}}"
