- name: variable from files
  hosts: localhost
  vars_files:
   - vars.yaml  #it wil read the variables from vars.yaml file 
  tasks:
    - name: print override info
      ansible.builtin.debug:
        msg: "hi iam learning course {{course}} from trainer {{trainer}},duration {{duration}}"
