- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:  # dnf to install packages
      name: "{{item.state}}"
      state: "{{item.state}}"
    loop:
    - {name: 'mysql', state: 'latest'} # item
    - {name: 'nginx', state: 'remove'}
    - {name: 'postfix', state: 'absent'}
     


    